blog/urls.py
from django.urls import path
from . import views



app_name = 'post'
urlpatterns = [
    path('', views.PostListView.as_view(), name='index'),
    path('<int:pk>/', views.PostDetailView.as_view(), name='detail'),
    path('new/', views.PostCreateView.as_view(), name='new'),
    path('<int:pk>/edit/', views.PostUpdateView.as_view(), name='edit'),
    path('<int:pk>/delete/', views.PostDeleteView.as_view(), name='delete'),
]

category/urls.py
from django.urls import path
from . import views

app_name = 'category'
urlpatterns = [
    path('', views.CategoryListView.as_view(), name='index'),
    path('<int:pk>/', views.CategoryDetailView.as_view(), name='detail'),
    path('new/', views.CategoryCreateView.as_view(), name='new'),
    path('<int:pk>/edit/', views.CategoryUpdateView.as_view(), name='edit'),
    path('<int:pk>/delete/', views.CategoryDeleteView.as_view(), name='delete'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),
    path('post/', include('blog.urls')),
    path('tag/', include('tag.urls')),
    path('category/', include('category.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', views.signup, name='signup'),
    path('accounts/', include('allauth.urls')),
    path('comments/', include('django_comments.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tag/urls.py
from django.urls import path
from . import views

app_name = 'tag'
urlpatterns = [
    path('', views.TagListView.as_view(), name='index'),
    path('<int:pk>/', views.TagDetailView.as_view(), name='detail'),
    path('new/', views.TagCreateView.as_view(), name='new'),
    path('<int:pk>/edit/', views.TagUpdateView.as_view(), name='edit'),
    path('<int:pk>/delete/', views.TagDeleteView.as_view(), name='delete'),
]

mysite/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

mysite/views.py
from django.contrib.auth import login, authenticate
from django.shortcuts import render, redirect
from .forms import SignUpForm
from category.models import Category
from blog.models import Post


def index(request):
    template = 'index.html'
    categories_with_posts = dict()
    for category in Category.objects.all():
        posts = Post.objects.filter(category=category.pk).order_by('-created')[:5]
        if posts:
            categories_with_posts[category] = posts
    context = {
        "categories_with_posts": categories_with_posts,
    }
    return render(request, template, context)


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('/')
    else:
        form = SignUpForm()
    return render(request, 'registration/signup.html', {'form': form})

mysite/templates/base.html
<!DOCTYPE html>
{% load auth_extras %}
{% load static %}
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

<html lang="en-US">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<title>News Site</title>
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

	<!-- STYLES -->
	<link rel="stylesheet" href='{% static "css/bootstrap.min.css" %}' type="text/css" media="all">
	<link rel="stylesheet" href='{% static "css/all.min.css" %}' media="all">
	<link rel="stylesheet" href='{% static "css/slick.css" %}' type="text/css" media="all">
	<link rel="stylesheet" href='{% static "css/simple-line-icons.css" %}' type="text/css" media="all">
	<link rel="stylesheet" href='{% static "css/style.css" %}' type="text/css" media="all">
</head>

<body>

<!-- site wrapper -->
<div class="site-wrapper">
	<div class="main-overlay"></div>
	<!-- header -->
	<header class="header-default">
		<nav class="navbar navbar-expand-lg">
			<div class="container-xl">
				<!-- site logo -->
				<a class="navbar-brand" href="/"></a>

				<div class="collapse navbar-collapse">
					<!-- menus -->
					<ul class="navbar-nav mr-auto">
						<li class="nav-item dropdown active">
							<a class="nav-link" href="/">Home</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="/post/">Посты</a>
						</li>
						<li class="nav-item dropdown">
							<a class="nav-link dropdown-toggle" href="{% url 'category:index' %}">Категории</a>
							<ul class="dropdown-menu">
								{% for cat in categories %}
								<li>
									<a class="dropdown-item" href="{% url 'category:detail' cat.id %}">	{{ cat.name }} </a>
								</li>
								{% endfor %}
							</ul>
						</li>
					</ul>
				</div>

				<!-- header right section -->
				<div class="header-right">
					<!-- header buttons -->
					<div class="header-buttons">
						{% if user.is_authenticated %}
							<button type="button" class="btn btn-default" onclick="document.location='/accounts/logout/'">
								<i class="far fa-user pr-2" aria-hidden="true">Выйти</i>
							</button>
						{% else %}
							<button type="button" class="btn btn-default" onclick="document.location='/accounts/login/'">
								<i class="far fa-user pr-2" aria-hidden="true">Войти</i>
							</button>
							<button type="button" class="btn btn-default" onclick="document.location='/accounts/signup/'">
								<i class="far fa-user pr-2" aria-hidden="true">Зарегистрироваться</i>
							</button>
						{% endif %}

						<button class="search icon-button">
							<i class="icon-magnifier"></i>
						</button>
						<button class="burger-menu icon-button">
							<span class="burger-icon"></span>
						</button>
					</div>
				</div>
			</div>
		</nav>
	</header>
	<!-- section main content -->
	<section class="main-content">
		<div class="container-xl">
			<div class="row gy-4">
				<div class="col-lg-8">
					{% block content %}{% endblock %}
				</div>
			<div class="col-lg-4">
				<!-- sidebar -->
				<div class="sidebar">
					<!-- widget about -->
					<div class="widget rounded">
						<div class="widget-about data-bg-image text-center" style="background-image: url('/static/images/map-bg.png');">
							<img src="/static/images/logo.svg" alt="logo" class="mb-4" />
							<p class="mb-4">Добро пожаловать на новостной сайт. Здесь вы можете найти самые актуальные новости.</p>
							<ul class="social-icons list-unstyled list-inline mb-0">
								<li class="list-inline-item"><a href="#"><i class="fab fa-facebook-f"></i></a></li>
								<li class="list-inline-item"><a href="#"><i class="fab fa-twitter"></i></a></li>
								<li class="list-inline-item"><a href="#"><i class="fab fa-instagram"></i></a></li>
								<li class="list-inline-item"><a href="#"><i class="fab fa-pinterest"></i></a></li>
								<li class="list-inline-item"><a href="#"><i class="fab fa-youtube"></i></a></li>
							</ul>
						</div>
					</div>

					<!-- widget categories -->
					<div class="widget rounded">
						<div class="widget-header text-center">
							<h3 class="widget-title">Наши Категории</h3>
							<img src="/static/images/wave.svg" class="wave" alt="wave" />
						</div>
						<div class="widget-content">
							<ul class="list">
								{% for cat in categories %}
									<li><a href="{% url 'category:detail' cat.pk %}">{{cat.name}}</a><span></span></li>
								{% endfor %}
							</ul>
						</div>

					</div>

					<!-- widget newsletter -->
					<div class="widget rounded">
						<div class="widget-header text-center">
							<h3 class="widget-title">Новостная рассылка</h3>
							<img src="/static/images/wave.svg" class="wave" alt="wave" />
						</div>
						<div class="widget-content">
							<span class="newsletter-headline text-center mb-3">Подписывайтесь и не упустите важную новость!</span>
							<form>
								<div class="mb-2">
									<input class="form-control w-100 text-center" placeholder="Email address…" type="email">
								</div>
								<button class="btn btn-default btn-full" type="submit">Подписаться</button>
							</form>
							<span class="newsletter-privacy text-center mt-3">Регистрируясь, вы соглашаетесь с нашей <a href="#">политикой конфиденциальности</a></span>
						</div>
					</div>

					<!-- widget tags -->
					<div class="widget rounded">
						<div class="widget-header text-center">
							<h3 class="widget-title">Навигатор тэгов</h3>
							<img src="/static/images/wave.svg" class="wave" alt="wave" />
						</div>
						<div class="widget-content">
							{% for tag in tags %}
								<a href="{% url 'tag:detail' tag.id %}" class="tag"> {{ tag.name }}</a>
							{% endfor %}
						</div>
					</div>
				</div>
			</div>
			</div>
		</div>
	</section>
	<!-- footer -->
	<footer>
		<div class="container-xl">
			<div class="footer-inner">
				<div class="row d-flex align-items-center gy-4">
					<!-- copyright text -->
					<div class="col-md-4">
						<span class="copyright">© 2022. Andrey's Workshop</span>
					</div>

					<!-- social icons -->
					<div class="col-md-4 text-center">
						<ul class="social-icons list-unstyled list-inline mb-0">
							<li class="list-inline-item"><a href="#"><i class="fab fa-facebook-f"></i></a></li>
							<li class="list-inline-item"><a href="#"><i class="fab fa-twitter"></i></a></li>
							<li class="list-inline-item"><a href="#"><i class="fab fa-instagram"></i></a></li>
							<li class="list-inline-item"><a href="#"><i class="fab fa-pinterest"></i></a></li>
							<li class="list-inline-item"><a href="#"><i class="fab fa-youtube"></i></a></li>
						</ul>
					</div>

					<!-- go to top button -->
					<div class="col-md-4">
						<a href="#" id="return-to-top" class="float-md-end"><i class="icon-arrow-up"></i>Back to Top</a>
					</div>
				</div>
			</div>
		</div>
	</footer>
</div>

</body>
</html>

mysite/templates/index.html
{% extends 'base.html' %}
{% block content %}

<section class="main-content">
	<div class="container-xl">
		<div class="row gy-4">
			{% if categories %}
				{% for category, posts in categories_with_posts.items %}
					<div class="col-md-12 col-sm-6 ">
						<div class=" clearfix">
						</div>
					</div>
						<div class="padding-30 rounded bordered">
							<div class="row gy-5">
								{% if posts %}
									{% for post in posts %}
										{% if forloop.first %}
											<div class="col-sm-6">
												<!-- post first-->
												<div class="post">
													<div class="thumb rounded">
														<a href="{% url 'category:detail' category.id %}" class="category-badge position-absolute">{{ category.name }}</a>
														<span class="post-format">
															<i class="icon-picture"></i>
														</span>
														<a href="{% url 'post:detail' post.id %}">
															<div class="inner">
																<img src="/media/{{ post.image }}" alt="{{ post.title }}">
															</div>
														</a>
													</div>
													<ul class="meta list-inline mt-1 mb-0">
														<li class="list-inline-item">{{ post.author}}</li>
														<li class="list-inline-item">{{ post.publish }}</li>
													</ul>
													<h5 class="post-title mb-3 mt-3"><a href="{% url 'post:detail' post.id %}">{{ post.title }}</a></h5>
													<p class="excerpt mb-0">{{ post.body|truncatewords:50|truncatechars:250 }}</p>
												</div>
											</div>
										<div class="col-sm-6">
										{% else %}
											<!-- rest posts -->

												<!-- post -->
												<div class="post post-list-sm square">
													<div class="thumb rounded">
														<a href="{% url 'post:detail' post.id %}">
															<div class="inner">
																<img src="/media/{{ post.image }}" alt="{{ post.title }}" />
															</div>
														</a>
													</div>
													<div class="details clearfix">
														<h6 class="post-title my-0"><a href="{% url 'post:detail' post.id %}">{{ post.title }}</a></h6>
														<ul class="meta list-inline mt-1 mb-0">
															<li class="list-inline-item">{{ post.publish }}</li>
														</ul>
													</div>
												</div>

										{% endif %}
									{% endfor %}
										</div>
								{% else %}
									<p>Нет доступных новостей.</p>
								{% endif %}
							</div>
						</div>
				{% endfor %}
			{% else %}
				<p>Нет доступных категорий.</p>
			{% endif %}
			<div class="spacer" data-height="50"></div>
		</div>
	</div>
</section>

{% endblock %}