blog/urls.py
from django.urls import path
from . import views



app_name = 'post'
urlpatterns = [
    path('', views.PostListView.as_view(), name='index'),
    path('<int:pk>/', views.PostDetailView.as_view(), name='detail'),
    path('new/', views.PostCreateView.as_view(), name='new'),
    path('<int:pk>/edit/', views.PostUpdateView.as_view(), name='edit'),
    path('<int:pk>/delete/', views.PostDeleteView.as_view(), name='delete'),
]

category/urls.py
from django.urls import path
from . import views

app_name = 'category'
urlpatterns = [
    path('', views.CategoryListView.as_view(), name='index'),
    path('<int:pk>/', views.CategoryDetailView.as_view(), name='detail'),
    path('new/', views.CategoryCreateView.as_view(), name='new'),
    path('<int:pk>/edit/', views.CategoryUpdateView.as_view(), name='edit'),
    path('<int:pk>/delete/', views.CategoryDeleteView.as_view(), name='delete'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),
    path('post/', include('blog.urls')),
    path('tag/', include('tag.urls')),
    path('category/', include('category.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', views.signup, name='signup'),
    path('accounts/', include('allauth.urls')),
    path('comments/', include('django_comments.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tag/urls.py
from django.urls import path
from . import views

app_name = 'tag'
urlpatterns = [
    path('', views.TagListView.as_view(), name='index'),
    path('<int:pk>/', views.TagDetailView.as_view(), name='detail'),
    path('new/', views.TagCreateView.as_view(), name='new'),
    path('<int:pk>/edit/', views.TagUpdateView.as_view(), name='edit'),
    path('<int:pk>/delete/', views.TagDeleteView.as_view(), name='delete'),
]

category/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=64, db_index=True, verbose_name='Название категории')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Категории'
        verbose_name = 'Категория'
        ordering = ['name']

    def get_absolute_url(self):
        return reverse('category:detail', args=[str(self.id)])

category/views.py
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from blog.models import Post
from django.contrib.auth.mixins import LoginRequiredMixin
from braces.views import GroupRequiredMixin
from .models import Category


class CategoryListView(ListView):
    model = Category
    template_name = 'category/index.html'


class CategoryDetailView(DetailView):
    model = Category
    template_name = 'category/detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        category = self.get_object()
        posts = Post.objects.filter(category=category.pk)
        context["posts"] = posts
        return context


class CategoryCreateView(LoginRequiredMixin, GroupRequiredMixin, CreateView):
    group_required = u"manager"
    model = Category
    template_name = 'category/new.html'
    fields = ['name']


class CategoryUpdateView(LoginRequiredMixin, GroupRequiredMixin, UpdateView):
    group_required = u"manager"
    model = Category
    template_name = 'category/edit.html'
    fields = ['name']


class CategoryDeleteView(LoginRequiredMixin, GroupRequiredMixin, DeleteView):
    group_required = u"manager"
    model = Category
    template_name = 'category/delete.html'
    success_url = reverse_lazy('category:index')

category/templates/category/delete.html
{% extends 'base.html' %}
{% block content %}
<div class="row gx-2 gx-lg-5 justify-content-center">
    <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="mb-2">
            <div class="form-control w-100 text-center">
                <h1>Удалить категорию</h1>
                <form action="" method="post">{% csrf_token %}
                  <h6>Вы уверены что хотите удалить "{{ category.name }}"?</h6>
                  <input class="btn btn-default btn-full " type="submit" value="Confirm" />
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

category/templates/category/detail.html
{% extends 'base.html' %}
{% load auth_extras %}

{% block content %}
<h1> Категория {{category.name}} </h1>

<div class="padding-30 rounded bordered">
	{% if request.user|has_group:"manager" %}
		<div class="mb-4">
			<a class="btn btn-default" href='{% url "category:edit" category.pk %}'>Редактировать категорию</a>
			<a class="btn btn-default" href='{% url "category:delete" category.pk %}'>Удалить категорию</a>
		</div>
	{% endif %}

	<div class="row">
		<div class="col-md-12 col-sm-6">
			{% if posts %}
				{% for post in posts %}
					<div class="post post-list clearfix">
						<div class="thumb rounded">
							<span class="post-format-sm">
								<i class="icon-picture"></i>
							</span>
							<a href="{% url 'post:detail' post.id %}">
								<div class="inner">
									<img src="/media/{{ post.image }}" alt="{{ post.title }}">
								</div>
							</a>
						</div>
						<div class="details">
							<ul class="meta list-inline mb-3">
								<li class="list-inline-item"><a href='{% url "category:detail" post.category.pk %}'> {{ post.category }} </a></li>
								<li class="list-inline-item"> {{ post.publish }} </li>
							</ul>
							<h5 class="post-title"><a href="{% url 'post:detail' post.id %}">{{ post.title }}</a></h5>
							<p class="excerpt mb-0"> {{ post.body|truncatewords:50 }} </p>
						</div>
					</div>
				{% endfor %}
			{% else %}
				<p>Нет доступных новостей.</p>
			{% endif %}
		</div>
	</div>
</div>
{% endblock %}

category/templates/category/edit.html
{% extends 'base.html' %}
{% block content %}
<div class="row gx-2 gx-lg-5 justify-content-center">
    <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="mb-2">
            <div class="form-control w-100 text-center">
                <style type="text/css">
                    input {
                    display: block;
                    border-radius: 25px;
                    width: 100%;
                    padding: 8px 24px;
                    font-size: 18px;
                    line-height: 1.6;
                    color: #fe6074;
                    background-color: #FFF;
                    background-image: none;
                    border: solid 2px #fe6074;
                    -webkit-box-shadow: none;
                    box-shadow: none;
                   }
                    textarea {
                    display: block;
                    border-radius: 25px;
                    width: 100%;
                    padding: 8px 24px;
                    font-size: 18px;
                    line-height: 1.6;
                    color: #fe6074;
                    background-color: #FFF;
                    background-image: none;
                    border: solid 2px #fe6074;
                    -webkit-box-shadow: none;
                    box-shadow: none;
                   }
                    label {
                        color: #000000;
                    }
                </style>
                <h1>Редактировать Категорию</h1>
                <form action="" method="post">{% csrf_token %}
                    {{ form.as_p }}
                    <button class="btn btn-default btn-full" type="submit">Сохранить</button>
                </form>
            </div>
        </div>
	</div>
</div>
{% endblock content %}

category/templates/category/index.html
{% extends 'base.html' %}
{% load auth_extras %}

{% block content %}
<h1> Доступные Категории </h1>
<div class="padding-30 rounded bordered">
	<div class="row">
		<div class="row gx-2 gx-lg-5 justify-content-left">
			{% if request.user|has_group:"manager" %}
				<div class="col-md-10 col-lg-8 col-xl-7 mb-4">
					<a class="btn btn-default" href='{% url "category:new" %}'>Создать категорию</a>
				</div>
			{% endif %}
		</div>
		{% if object_list %}
			{% for category in object_list %}
				<div class="col-md-12 col-sm-6 ">
					<div class="post post-list clearfix">
						<h5 class="post-title"><a href="{% url 'category:detail' category.id %}">{{ category.name }}</a></h5>
					</div>
				</div>
			{% endfor %}
		{% else %}
			<p>Нет доступных категорий.</p>
		{% endif %}
	</div>
</div>
{% endblock %}

category/templates/category/new.html
{% extends 'base.html' %}
{% block content %}
<div class="row gx-2 gx-lg-5 justify-content-center">
    <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="mb-2">
            <div class="form-control w-100 text-center">
                 <style type="text/css">
                   input {
                   display: block;
                    border-radius: 25px;
                    width: 100%;
                    padding: 8px 24px;
                    font-size: 18px;
                    line-height: 1.6;
                    color: #fe6074;
                    background-color: #FFF;
                    background-image: none;
                    border: solid 2px #fe6074;
                    -webkit-box-shadow: none;
                    box-shadow: none;
                   }
                   textarea {
                   display: block;
                    border-radius: 25px;
                    width: 100%;
                    padding: 8px 24px;
                    font-size: 18px;
                    line-height: 1.6;
                    color: #fe6074;
                    background-color: #FFF;
                    background-image: none;
                    border: solid 2px #fe6074;
                    -webkit-box-shadow: none;
                    box-shadow: none;
                   }
                    label {
                        color: #000000;
                    }
                 </style>
                <h1>Создать Категорию</h1>
                <form action="" method="post">{% csrf_token %}
                 {{ form.as_p }}
                     <button class="btn btn-default btn-full" type="submit">Сохранить</button>
                </form>
            </div>
        </div>
	</div>
</div>
{% endblock content %}