blog/urls.py
from django.urls import path
from . import views



app_name = 'post'
urlpatterns = [
    path('', views.PostListView.as_view(), name='index'),
    path('<int:pk>/', views.PostDetailView.as_view(), name='detail'),
    path('new/', views.PostCreateView.as_view(), name='new'),
    path('<int:pk>/edit/', views.PostUpdateView.as_view(), name='edit'),
    path('<int:pk>/delete/', views.PostDeleteView.as_view(), name='delete'),
]

category/urls.py
from django.urls import path
from . import views

app_name = 'category'
urlpatterns = [
    path('', views.CategoryListView.as_view(), name='index'),
    path('<int:pk>/', views.CategoryDetailView.as_view(), name='detail'),
    path('new/', views.CategoryCreateView.as_view(), name='new'),
    path('<int:pk>/edit/', views.CategoryUpdateView.as_view(), name='edit'),
    path('<int:pk>/delete/', views.CategoryDeleteView.as_view(), name='delete'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),
    path('post/', include('blog.urls')),
    path('tag/', include('tag.urls')),
    path('category/', include('category.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', views.signup, name='signup'),
    path('accounts/', include('allauth.urls')),
    path('comments/', include('django_comments.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tag/urls.py
from django.urls import path
from . import views

app_name = 'tag'
urlpatterns = [
    path('', views.TagListView.as_view(), name='index'),
    path('<int:pk>/', views.TagDetailView.as_view(), name='detail'),
    path('new/', views.TagCreateView.as_view(), name='new'),
    path('<int:pk>/edit/', views.TagUpdateView.as_view(), name='edit'),
    path('<int:pk>/delete/', views.TagDeleteView.as_view(), name='delete'),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import User
from category.models import Category
from tag.models import Tag


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='posts', null=True, blank=True)
    body = models.TextField()
    tags = models.ManyToManyField(Tag)
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')
    category = models.ForeignKey(Category, models.SET_NULL, blank=True, null=True)
    image = models.ImageField(upload_to='uploads/%Y/%m/%d/', height_field=None, default='std_img.jpg')

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post:detail', args=[str(self.id)])

blog/views.py
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from braces.views import GroupRequiredMixin

from .models import Post


class PostListView(ListView):
    model = Post
    template_name = 'post/index.html'


class PostDetailView(DetailView):
    model = Post
    template_name = 'post/detail.html'


class PostCreateView(LoginRequiredMixin, GroupRequiredMixin, CreateView):
    group_required = u"manager"
    model = Post
    template_name = 'post/new.html'
    fields = ['title', 'body', 'image', 'status', 'category', 'tags']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostUpdateView(LoginRequiredMixin, GroupRequiredMixin, UpdateView):
    group_required = u"manager"
    model = Post
    template_name = 'post/edit.html'
    fields = ['title', 'body', 'image', 'status', 'category', 'tags']


class PostDeleteView(LoginRequiredMixin, GroupRequiredMixin, DeleteView):
    group_required = u"manager"
    model = Post
    template_name = 'post/delete.html'
    success_url = reverse_lazy('post:index')

blog/templates/post/delete.html
{% extends 'base.html' %}

{% block content %}
<div class="row gx-2 gx-lg-5 justify-content-center">
    <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="mb-2">
            <div class="form-control w-100 text-center">
                <h1>Удалить пост</h1>
                <form action="" method="post">{% csrf_token %}
                  <h6>Вы уверены что хотите удалить "{{ post.title }}"?</h6>
                  <input class="btn btn-default btn-full " type="submit" value="Confirm" />
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

blog/templates/post/detail.html
{% extends 'base.html' %}
{% load auth_extras %}
{% load comments %}
{% block content %}
<div class="post post-single col-lg-8">
    <!-- post header -->
    <div class="post-header">
        <h1 class="title mt-0 mb-3">{{post.title}}</h1>
        <ul class="meta list-inline mb-0">
            <li class="list-inline-item"> {{post.author }} </li>
            <li class="list-inline-item"><a href="{% url 'category:detail' post.category.pk %}"> {{ post.category}} </a></li>
            <li class="list-inline-item">{{ post.publish }}</li>
        </ul>
    </div>

    <!-- featured image -->
    <div class="featured-image">
        <img src="/media/{{ post.image }}" alt="post-title">
    </div>
    <!-- post content -->
    <div class="post-content clearfix">
        <p> {{post.body}} </p>
    </div>
    <!-- post bottom section -->
    <div class="post-bottom">
<!--        <div class="row d-flex align-items-center">-->
            <div class="col-md-6 col-12 text-center text-md-start">
                <!-- tags -->
                {% for tag in post.tags.all %}
                    <a href="{% url 'tag:detail' tag.id %}" class="tag"> {{ tag.name }}</a>
                {% endfor %}
            </div>
<!--        </div>-->
    </div>
</div>

<div class="row gx-2 gx-sm-5 justify-content-left">
		 <div class="col-md-10 col-lg-8 col-xl-7">
         {% if request.user|has_group:"manager" %}
            <a  class="btn btn-default mt-4 mb-4" href='{% url "post:edit" post.pk %}'>Редактировать пост</a>
            <a class="btn btn-default" href='{% url "post:delete" post.pk %}'>Удалить пост</a>
        {% endif %}
<style>
input {
    display: block;
    border-radius: 25px;
    width: 100%;
    padding: 8px 24px;
    font-size: 18px;
    line-height: 1.6;
    color: #fe6074;
    background-color: #FFF;
    background-image: none;
    border: solid 2px #fe6074;
    -webkit-box-shadow: none;
    box-shadow: none;
   }
    textarea {
    display: block;
    border-radius: 25px;
    width: 100%;
    padding: 8px 24px;
    font-size: 18px;
    line-height: 1.6;
    color: #fe6074;
    background-color: #FFF;
    background-image: none;
    border: solid 2px #fe6074;
    -webkit-box-shadow: none;
    box-shadow: none;
   }
    label {
        color: #000000;
    }
</style>
{% render_comment_list for post %}
    {% if user.is_authenticated %}
        {% get_comment_form for object as form %}
        <form action="{% comment_form_target %}" method="POST">
        {% csrf_token %}
        {{ form.comment }}
        {{ form.content_type }}
        {{ form.object_pk }}
        {{ form.timestamp }}
        {{ form.security_hash }}
        <input  type="hidden" name="next" value="{% url 'post:detail' post.id %}" />
        <input class="mt-2 btn btn-default" type="submit" value="Добавить комментарий" id="id_submit" />
        </form>
    {% else %}
        <h6>Пожалуйста <a href="/accounts/login/">войдите</a> чтобы оставить комментарий.</h6>
    {% endif %}
     </div>
</div>
{% endblock %}

blog/templates/post/edit.html
{% extends 'base.html' %}
{% block content %}
<div class="row gx-2 gx-lg-5 justify-content-center">
    <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="mb-2">
            <div class="form-control w-100 text-center">
                 <style type="text/css">
                   input {
                   display: block;
                    border-radius: 25px;
                    width: 100%;
                    padding: 8px 24px;
                    font-size: 18px;
                    line-height: 1.6;
                    color: #fe6074;
                    background-color: #FFF;
                    background-image: none;
                    border: solid 2px #fe6074;
                    -webkit-box-shadow: none;
                    box-shadow: none;
                   }
                   textarea {
                   display: block;
                    border-radius: 25px;
                    width: 100%;
                    padding: 8px 24px;
                    font-size: 18px;
                    line-height: 1.6;
                    color: #fe6074;
                    background-color: #FFF;
                    background-image: none;
                    border: solid 2px #fe6074;
                    -webkit-box-shadow: none;
                    box-shadow: none;
                   }
                    label {
                        color: #000000;
                    }
                 </style>
                <h1>Редактировать Пост</h1>
                <form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
                 {{ form.as_p }}
                     <button class="btn btn-default btn-full" type="submit">Сохранить</button>
                </form>
            </div>
        </div>
	</div>
</div>
{% endblock content %}

blog/templates/post/index.html
{% extends 'base.html' %}
{% load auth_extras %}
{% block content %}

<div class="padding-30 rounded bordered">
	{% if request.user|has_group:"manager" %}
		<div class="mb-4">
			<a class="btn btn-default" href='{% url "post:new" %}'>Новый пост</a>
		</div>
	{% endif %}
	<div class="row">
		{% if object_list %}
			{% for post in object_list %}
				<div class="col-md-12 col-sm-6">
					<div class="post post-list clearfix">
						<div class="thumb rounded">
							<span class="post-format-sm">
								<i class="icon-picture"></i>
							</span>
							<a href="{% url 'post:detail' post.id %}">
								<div class="inner">
									{% if post.image %}
									<img src="/media/{{ post.image }}" alt="post-title">
									{% else %}
										<img src="/meida/std_img.jpg" alt="post-title">
									{% endif %}
								</div>
							</a>
						</div>
						<div class="details">
							<ul class="meta list-inline mb-3">
								<li class="list-inline-item"> {{post.author }} </li>
								<li class="list-inline-item"><a href='{% url "category:detail" post.category.pk %}'> {{ post.category }} </a></li>
								<li class="list-inline-item"> {{ post.publish }} </li>
							</ul>
							<h5 class="post-title"><a href="{% url 'post:detail' post.id %}">{{ post.title }}</a></h5>
							<p class="excerpt mb-0"> {{ post.body|truncatewords:50 }} </p>
						</div>
					</div>
				</div>
			{% endfor %}
		{% else %}
			<p>Нет доступных постов.</p>
	{% endif %}
	</div>
</div>

{% endblock %}

blog/templates/post/new.html
{% extends 'base.html' %}
{% block content %}
<div class="row gx-2 gx-lg-5 justify-content-center">
    <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="mb-2">
            <div class="form-control w-100 text-center">
                 <style type="text/css">
                   input {
                   display: block;
                    border-radius: 25px;
                    width: 100%;
                    padding: 8px 24px;
                    font-size: 18px;
                    line-height: 1.6;
                    color: #fe6074;
                    background-color: #FFF;
                    background-image: none;
                    border: solid 2px #fe6074;
                    -webkit-box-shadow: none;
                    box-shadow: none;
                   }
                   textarea {
                   display: block;
                    border-radius: 25px;
                    width: 100%;
                    padding: 8px 24px;
                    font-size: 18px;
                    line-height: 1.6;
                    color: #fe6074;
                    background-color: #FFF;
                    background-image: none;
                    border: solid 2px #fe6074;
                    -webkit-box-shadow: none;
                    box-shadow: none;
                   }
                    label {
                        color: #000000;
                    }
                 </style>
                <h1>Новый пост</h1>
                <form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
                 {{ form.as_p }}
                     <button class="btn btn-default btn-full" type="submit">Сохранить</button>
                </form>
            </div>
        </div>
	</div>
</div>
{% endblock content %}